import { useState } from 'react'
import {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Check,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Clock3,
  Download,
  ExternalLink,
  FileSpreadsheet,
  Gift,
  Globe2,
  Layers3,
  Link2,
  LockKeyhole,
  Mail,
  MousePointer2,
  PlugZap,
  Send,
  ShieldCheck,
  Sparkles,
  Table2,
  Users,
  WalletCards,
  Workflow,
  X,
  Zap,
} from 'lucide-react'
import './commercialRecordPages.css'

const localize = (record, zh, en) => (record?.locale === 'en' ? en : zh)
const routeLocale = (record) => (record?.locale === 'en' ? '/en' : '')
const sectionText = (record, index, fallback) => record?.sections?.[index]?.text || fallback
const internalPath = (record, path) => `${routeLocale(record)}${path}`

function BoundaryNote({ record, children }) {
  return <div className="commercial-boundary-note"><ShieldCheck size={18} /><p>{children || localize(record, '本地重建仅呈现公开页面结构；账户、支付、插件下载、同步服务和后端任务尚未接入。', 'This local rebuild presents public page structure only. Accounts, payments, extension downloads, sync services, and backend jobs are not connected.')}</p></div>
}

function RouteButton({ record, onNavigate, path, children, className = 'button button-primary' }) {
  return <button className={className} onClick={() => onNavigate(internalPath(record, path))}>{children}<ArrowRight size={16} /></button>
}

function PreviewAction({ children, icon: Icon = LockKeyhole }) {
  return <button type="button" className="commercial-preview-action" disabled><Icon size={16} />{children}</button>
}

function CommercialHeader({ record, onNavigate, label }) {
  return <div className="commercial-record-header page-shell">
    <button className="commercial-record-breadcrumb" onClick={() => onNavigate(routeLocale(record) || '/')}><span className="commercial-record-mark">M</span><span>MediaClaw</span><ChevronRight size={14} /><span>{label}</span></button>
    <span className="commercial-record-status"><span className="commercial-status-dot" /> {localize(record, '公开结构 · 预览', 'Public structure · preview')}</span>
  </div>
}

function DownloadRecordPage({ record, onNavigate }) {
  const isEnglish = record.locale === 'en'
  const steps = isEnglish
    ? [['01', 'Install extension', 'Choose a browser store. The real store download is not connected in this rebuild.'], ['02', 'Open a public page', 'Visit a public Xiaohongshu or Douyin page in the same browser.'], ['03', 'Start the workflow', 'The extension would recognize the page and expose the matching action.']]
    : [['01', '安装插件', '选择浏览器商店；当前重建未接通真实商店下载。'], ['02', '打开公开页面', '在同一浏览器打开小红书或抖音的公开页面。'], ['03', '发起工作流', '真实插件会识别页面并展示对应的采集或分析动作。']]
  return <main className="commercial-record commercial-download-record">
    <CommercialHeader record={record} onNavigate={onNavigate} label={localize(record, '下载插件', 'Download')} />
    <section className="commercial-download-hero page-shell">
      <div className="commercial-download-copy"><span className="commercial-eyebrow"><Download size={15} /> {localize(record, '浏览器插件', 'Browser extension')}</span><h1>{record.h1}</h1><p>{record.summary}</p><div className="commercial-hero-actions"><PreviewAction icon={Download}>{localize(record, '安装插件（预览）', 'Install extension (preview)')}</PreviewAction><RouteButton record={record} onNavigate={onNavigate} path="/pricing" className="button button-soft">{localize(record, '查看价格方案', 'View pricing')}</RouteButton></div><BoundaryNote record={record}>{localize(record, '商店下载、激活码购买和登录配置未接入；按钮仅保留真实流程位置，不会伪造下载成功。', 'Store download, activation-code checkout, and login setup are not connected. Actions preserve the real flow without claiming a successful download.')}</BoundaryNote></div>
      <div className="commercial-browser-preview" aria-label={localize(record, '插件安装预览', 'Extension install preview')}><div className="commercial-browser-bar"><span /><span /><span /><b>{isEnglish ? 'mediaclaw.app / download' : 'mediaclaw.app / download'}</b></div><div className="commercial-browser-body"><div className="commercial-browser-page"><span className="commercial-browser-line long" /><span className="commercial-browser-line" /><span className="commercial-browser-line short" /><div className="commercial-browser-media" /></div><div className="commercial-extension-panel"><div className="commercial-extension-brand"><span className="commercial-record-mark">M</span><strong>MediaClaw</strong><span className="commercial-live-dot" /></div><small>{isEnglish ? 'Current public page detected' : '已识别当前公开页面'}</small><strong>{isEnglish ? 'Ready to collect' : '可以开始采集'}</strong><p>{isEnglish ? 'Posts, comments and media' : '笔记、评论与媒体素材'}</p><span className="commercial-panel-button">{isEnglish ? 'Start workflow' : '开始工作流'} <ArrowRight size={13} /></span></div></div></div>
    </section>
    <section className="commercial-download-steps section-band"><div className="page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Workflow size={15} /> {localize(record, '三步上手', 'Three steps')}</span><h2>{sectionText(record, 1, localize(record, '下载并安装 MediaClaw', 'Download and install MediaClaw'))}</h2><p>{localize(record, '安装、打开、开始采集；每一步都对应一个可检查的浏览器动作。', 'Install, open, and start a workflow. Each step maps to a browser action you can verify.')}</p></div><div className="commercial-step-grid">{steps.map(([number, title, copy]) => <article key={number}><span className="commercial-step-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div><ChevronRight size={18} /></article>)}</div></div></section>
    <section className="commercial-install-options page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Globe2 size={15} /> {localize(record, '安装渠道', 'Install channels')}</span><h2>{localize(record, '先选择你的浏览器', 'Choose your browser')}</h2></div><div className="commercial-channel-grid"><article><div className="commercial-icon-tile chrome">C</div><div><h3>{sectionText(record, 3, localize(record, 'Chrome 应用商店', 'Chrome Web Store'))}</h3><p>{localize(record, '公开页面中的商店入口，当前仅作结构预览。', 'The public store entry is represented as a structure preview.')}</p></div><PreviewAction icon={ExternalLink}>{localize(record, '商店入口未接入', 'Store unavailable')}</PreviewAction></article><article><div className="commercial-icon-tile edge">E</div><div><h3>{sectionText(record, 4, localize(record, 'Microsoft Edge 加载项', 'Microsoft Edge Add-ons'))}</h3><p>{localize(record, 'Edge 安装路径与 Chrome 分开保留，真实安装需接入商店。', 'The Edge path is kept separate from Chrome; real installation needs the store connection.')}</p></div><PreviewAction icon={ExternalLink}>{localize(record, '商店入口未接入', 'Store unavailable')}</PreviewAction></article></div></section>
    <section className="commercial-download-next section-band"><div className="page-shell commercial-download-next-grid"><div><span className="commercial-eyebrow"><Zap size={15} /> {localize(record, '安装之后', 'After installation')}</span><h2>{localize(record, '从激活到第一次采集，路径保持清楚', 'A clear path from activation to the first workflow')}</h2><p>{localize(record, '正式版激活和教程配置都是下一步操作；本地重建只展示入口，不会生成激活或同步结果。', 'Activation and tutorial setup are the next steps. This rebuild shows their entry points without generating an activation or sync result.')}</p></div><div className="commercial-next-list"><button onClick={() => onNavigate(internalPath(record, '/pricing?source=onboarding&entry=download_page'))}><span>01</span><strong>{sectionText(record, 5, localize(record, '购买正式版激活码', 'Buy an activation code'))}</strong><ArrowRight size={16} /></button><button type="button" disabled><span>02</span><strong>{sectionText(record, 6, localize(record, '跟随教程配置', 'Follow setup tutorial'))}</strong><LockKeyhole size={16} /></button></div></div></section>
    <section className="commercial-record-cta"><div className="page-shell commercial-cta-row"><div><span className="commercial-eyebrow">MediaClaw</span><h2>{localize(record, '先用免费版跑一次，再决定是否升级', 'Run the free path once, then decide whether to upgrade')}</h2></div><RouteButton record={record} onNavigate={onNavigate} path="/pricing" className="button button-dark">{localize(record, '查看价格', 'View pricing')}</RouteButton></div></section>
  </main>
}

const pricingPlans = {
  zh: [
    { name: '免费版', price: '¥0', note: '永久免费', copy: '适合偶尔做内容研究的个人', features: ['单篇深度采集', '基础列表采集', 'CSV / Markdown 导出', '无水印素材下载'] },
    { name: '个人版', price: '¥25', note: '年度合计 ¥299', copy: '适合持续做选题与内容运营的创作者', features: ['包含免费版全部能力', '批量增强与筛选', '飞书多维表同步', '含 1,500 积分'], featured: true },
    { name: '团队版', price: '¥58', note: '年度合计 ¥699', copy: '适合品牌、MCN 和多人的内容团队', features: ['包含个人版全部能力', '团队数据协作', '共享 5,000 积分', '多设备工作流'] },
  ],
  en: [
    { name: 'Free', price: '¥0', note: 'Forever free', copy: 'For occasional content research', features: ['Single-item deep collection', 'Basic list collection', 'CSV / Markdown export', 'Watermark-free media download'] },
    { name: 'Personal', price: '¥25', note: '¥299 billed yearly', copy: 'For creators running a consistent workflow', features: ['Everything in Free', 'Batch enhancement and filters', 'Lark Base sync', '1,500 credits included'], featured: true },
    { name: 'Team', price: '¥58', note: '¥699 billed yearly', copy: 'For brands, MCNs, and content teams', features: ['Everything in Personal', 'Team data collaboration', '5,000 shared credits', 'Multi-device workflows'] },
  ],
}

function PricingRecordPage({ record, onNavigate }) {
  const isEnglish = record.locale === 'en'
  const [billing, setBilling] = useState('yearly')
  const [openFaq, setOpenFaq] = useState(0)
  const plans = pricingPlans[isEnglish ? 'en' : 'zh'].map((plan) => billing === 'monthly' && plan.price !== '¥0' ? { ...plan, price: plan.name === (isEnglish ? 'Personal' : '个人版') ? '¥39' : '¥88', note: isEnglish ? 'Billed monthly' : '按月购买' } : plan)
  const faqs = isEnglish
    ? [['Will I be charged automatically?', 'No automatic renewal is represented here. Checkout is not connected, so confirm the final terms on the live service before purchasing.'], ['How is MediaClaw different from other scraping extensions?', 'The public positioning combines collection, analysis, export, and team handoff. The local page does not claim connected backend capacity.'], ['What are credits? Do they expire?', 'Credits are described as task capacity for AI, OCR, or transcription. Expiry and accounting rules require the live service to confirm.'], ['What if I run out of credits?', 'The public structure points to a credit-pack path. This preview does not process a top-up.'], ['How long does the Free plan last?', 'The route describes the Free plan as ongoing; account and entitlement verification are not connected here.']]
    : [['会自动扣费吗？', '页面按不自动续费的公开说明呈现；结算未接入，实际购买前仍应以真实服务条款为准。'], ['MediaClaw 和其他采集插件有什么区别？', '公开定位把采集、分析、导出和团队协作放在同一条工作流中；本地页面不宣称后端已可用。'], ['积分是什么？会过期吗？', '积分用于 AI、OCR 或逐字稿等任务；具体过期和扣减规则需要以真实服务确认。'], ['积分不够用怎么办？', '公开结构提供积分包路径；当前预览不会处理充值或扣款。'], ['免费版能用多久？', '页面将免费版描述为长期可用；账户权益校验未在本地重建中接入。']]
  return <main className="commercial-record commercial-pricing-record">
    <CommercialHeader record={record} onNavigate={onNavigate} label={localize(record, '价格方案', 'Pricing')} />
    <section className="commercial-pricing-hero page-shell"><div><span className="commercial-eyebrow"><CircleDollarSign size={15} /> {localize(record, '价格方案', 'Pricing')}</span><h1>{record.h1}</h1><p>{record.summary}</p></div><div className="commercial-price-promise"><BadgeCheck size={19} /><strong>{localize(record, '不自动续费', 'No automatic renewal')}</strong><span>{localize(record, '一次购买一个周期，到期自动停止', 'One period at a time; it stops at expiry')}</span></div></section>
    <section className="commercial-pricing-board page-shell"><div className="commercial-billing-tabs" role="tablist"><button className={billing === 'yearly' ? 'active' : ''} onClick={() => setBilling('yearly')} role="tab" aria-selected={billing === 'yearly'}>{localize(record, '年付', 'Yearly')}<small>{localize(record, '省 60%', 'Save 60%')}</small></button><button className={billing === 'monthly' ? 'active' : ''} onClick={() => setBilling('monthly')} role="tab" aria-selected={billing === 'monthly'}>{localize(record, '月付', 'Monthly')}</button></div><div className="commercial-plan-grid">{plans.map((plan) => <article key={plan.name} className={plan.featured ? 'commercial-plan-card featured' : 'commercial-plan-card'}><div className="commercial-plan-name"><span>{plan.name}</span>{plan.featured && <b>{localize(record, '推荐', 'Popular')}</b>}</div><p>{plan.copy}</p><div className="commercial-plan-price"><strong>{plan.price}</strong><span>{plan.name === (isEnglish ? 'Free' : '免费版') ? '' : localize(record, '/ 月', '/ month')}</span></div><small className="commercial-plan-note">{plan.note}</small><ul>{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><RouteButton record={record} onNavigate={onNavigate} path="/download" className={plan.featured ? 'button button-primary full' : 'button button-soft full'}>{localize(record, '免费安装', 'Install free')}</RouteButton></article>)}</div><BoundaryNote record={record}>{localize(record, '卡片中的价格和权益保留公开页面展示；支付、登录、激活和订单状态未接通，按钮不会伪造购买成功。', 'Displayed prices and benefits follow the public route; payment, login, activation, and order state are not connected, so buttons never claim a successful purchase.')}</BoundaryNote></section>
    <section className="commercial-feature-compare section-band"><div className="page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Layers3 size={15} /> {sectionText(record, 4, localize(record, '功能对比', 'Compare all features'))}</span><h2>{localize(record, '按你的工作节奏选择能力', 'Choose capabilities for your working rhythm')}</h2></div><div className="commercial-compare-table"><div className="commercial-compare-row header"><strong>{localize(record, '能力', 'Capability')}</strong><span>{localize(record, '免费版', 'Free')}</span><span>{localize(record, '个人版', 'Personal')}</span><span>{localize(record, '团队版', 'Team')}</span></div>{[[localize(record, '单篇深度采集', 'Deep collection'), 'check', 'check', 'check'], [localize(record, '批量增强与筛选', 'Batch enhancement'), '', 'check', 'check'], [localize(record, '飞书 / Lark 同步', 'Feishu / Lark sync'), '', 'check', 'check'], [localize(record, '团队协作', 'Team collaboration'), '', '', 'check']].map(([name, free, personal, team]) => <div className="commercial-compare-row" key={name}><strong>{name}</strong>{[free, personal, team].map((value, index) => <span key={index}>{value ? <Check size={16} /> : '—'}</span>)}</div>)}</div></div></section>
    <section className="commercial-pricing-faq page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Sparkles size={15} /> FAQ</span><h2>{sectionText(record, 5, localize(record, '常见问题', 'Frequently asked questions'))}</h2></div><div className="commercial-faq-list">{faqs.map(([question, answer], index) => <div className={openFaq === index ? 'open' : ''} key={question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span>{openFaq === index ? <X size={17} /> : <ChevronDown size={17} />}</button>{openFaq === index && <p>{answer}</p>}</div>)}</div></section>
    <section className="commercial-record-cta"><div className="page-shell commercial-cta-row"><div><span className="commercial-eyebrow"><Download size={15} /> {localize(record, '从免费版开始', 'Start free')}</span><h2>{sectionText(record, 11, localize(record, '先免费装上，跑一次再决定', 'Install it free, run it once, then decide'))}</h2></div><RouteButton record={record} onNavigate={onNavigate} path="/download" className="button button-dark">{localize(record, '免费安装插件', 'Install extension')}</RouteButton></div></section>
  </main>
}

const feishuCards = (record) => record.locale === 'en'
  ? [['One-click sync to Lark Base', 'Send structured titles, authors, metrics, comments, and source links into a team-owned table.', Table2], ['Multi-table schema', 'Keep collection, analysis, leads, and monitoring in separate views that match the work.', Layers3], ['Monitoring reports to Lark', 'A future connected workflow can route review-ready updates to a shared team entry point.', Send]]
  : [['采集结果一键同步飞书', '把标题、作者、互动、评论和来源链接整理到团队自己的多维表。', Table2], ['多表分层适配业务', '按采集、分析、客资和监控拆分视图，让每一类工作都有清楚的落点。', Layers3], ['监控日报推送飞书', '接入后可把值得复核的更新路由到团队入口；当前页面不伪造推送结果。', Send]]

function FeishuRecordPage({ record, onNavigate }) {
  const isEnglish = record.locale === 'en'
  const [openFaq, setOpenFaq] = useState(0)
  const faqs = isEnglish ? [['Is sync automatic or manually triggered?', 'The public route describes both a collection trigger and a team handoff. This rebuild does not connect either service.'], ['How do monitoring reports reach Lark?', 'The intended path is a Lark Base or alert destination configured by the team. No report is sent from this preview.'], ['Can multiple team members use the same Lark Base?', 'A team-owned Base is the intended collaboration boundary; permissions and schema provisioning still require a live integration.'], ['Do I need technical skills to set up the integration?', 'The public page positions setup as approachable, but this local preview does not run authorization or field mapping.']] : [['飞书同步是自动还是手动触发？', '公开页面同时保留采集触发和团队交接入口；本地重建没有连接任一服务。'], ['监控日报如何推送到飞书？', '预期路径是由团队配置飞书多维表或提醒目标；当前预览不会发送日报。'], ['团队成员可以共用同一份飞书表吗？', '团队自有多维表是协作边界；权限和字段配置仍需要真实集成完成。'], ['没有技术背景也能完成接入吗？', '公开页面把接入定位为易上手，但本地预览不会执行授权或字段映射。']]
  return <main className="commercial-record commercial-feishu-record">
    <CommercialHeader record={record} onNavigate={onNavigate} label={localize(record, '飞书集成', 'Lark integration')} />
    <section className="commercial-feishu-hero page-shell"><div className="commercial-feishu-copy"><span className="commercial-eyebrow"><Table2 size={15} /> {localize(record, '团队协作中台', 'Team workspace')}</span><h1>{record.h1}</h1><p>{record.summary}</p><div className="commercial-hero-actions"><RouteButton record={record} onNavigate={onNavigate} path="/download" className="button button-primary">{localize(record, '免费下载使用', 'Download free')}</RouteButton><RouteButton record={record} onNavigate={onNavigate} path="/pricing" className="button button-soft">{localize(record, '查看定价', 'View pricing')}</RouteButton></div><BoundaryNote record={record}>{localize(record, '飞书授权、字段映射和同步动作未接入；本页展示的是可审阅的工作流结构，不代表数据已写入飞书。', 'Lark authorization, field mapping, and sync actions are not connected. This page shows a reviewable workflow, not data written to Lark.')}</BoundaryNote></div><div className="commercial-flow-visual"><div className="commercial-flow-node source"><MousePointer2 size={19} /><strong>{localize(record, '公开页面', 'Public page')}</strong><small>{localize(record, '采集结果', 'Collected record')}</small></div><ArrowRight className="commercial-flow-arrow" /><div className="commercial-flow-node base"><Table2 size={21} /><strong>{localize(record, '飞书多维表', 'Lark Base')}</strong><small>{localize(record, '团队共享数据', 'Shared team data')}</small></div><ArrowRight className="commercial-flow-arrow" /><div className="commercial-flow-node team"><Users size={20} /><strong>{localize(record, '团队动作', 'Team action')}</strong><small>{localize(record, '复核与分配', 'Review and assign')}</small></div><span className="commercial-flow-caption">{localize(record, '同步连接 · 预览', 'Sync connection · preview')}</span></div></section>
    <section className="commercial-feishu-capabilities section-band"><div className="page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><PlugZap size={15} /> {sectionText(record, 1, localize(record, '飞书协作能力一屏看懂', 'Lark Base capabilities at a glance'))}</span><h2>{localize(record, '把结果交给真正要继续工作的人', 'Put results where the team can act on them')}</h2></div><div className="commercial-capability-grid">{feishuCards(record).map(([title, copy, Icon], index) => <article key={title}><span className="commercial-card-index">0{index + 1}</span><div className="commercial-icon-tile"><Icon size={20} /></div><h3>{title}</h3><p>{copy}</p><PreviewAction icon={LockKeyhole}>{localize(record, '同步未接入', 'Sync not connected')}</PreviewAction></article>)}</div></div></section>
    <section className="commercial-feishu-workflow page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Workflow size={15} /> {localize(record, '从数据到协作', 'From data to collaboration')}</span><h2>{localize(record, '一条记录如何进入团队节奏', 'How one record enters the team rhythm')}</h2></div><div className="commercial-workflow-list">{[['01', localize(record, '采集公开内容', 'Collect public content'), localize(record, '保留标题、作者、互动、原始链接和采集上下文。', 'Keep title, author, metrics, source links, and collection context.')], ['02', localize(record, '映射到业务字段', 'Map to business fields'), localize(record, '按团队需要把内容、评论、客资或监控记录放入对应表。', 'Place content, comments, leads, or monitoring records into the right table.')], ['03', localize(record, '分配下一步动作', 'Assign the next action'), localize(record, '团队成员继续复核、标记、导出或进入创作流程。', 'Teammates review, tag, export, or move the record into production.')]].map(([number, title, copy]) => <article key={number}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div><ChevronRight size={18} /></article>)}</div></section>
    <section className="commercial-feishu-faq section-band"><div className="page-shell commercial-faq-columns"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Sparkles size={15} /> FAQ</span><h2>{sectionText(record, 8, localize(record, '常见问题', 'Frequently asked questions'))}</h2><p>{localize(record, '先理解边界，再决定是否连接团队自己的飞书空间。', 'Understand the boundary before connecting your team workspace.')}</p></div><div className="commercial-faq-list">{faqs.map(([question, answer], index) => <div className={openFaq === index ? 'open' : ''} key={question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span>{openFaq === index ? <X size={17} /> : <ChevronDown size={17} />}</button>{openFaq === index && <p>{answer}</p>}</div>)}</div></div></section>
    <section className="commercial-related page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><ArrowUpRight size={15} /> {sectionText(record, 13, localize(record, '继续探索相关能力', 'Explore related tools'))}</span><h2>{localize(record, '从平台采集进入协作', 'Move from platform collection into collaboration')}</h2></div><div className="commercial-related-grid"><button onClick={() => onNavigate(internalPath(record, '/xiaohongshu'))}><strong>{localize(record, '小红书内容工作流', 'Xiaohongshu workflow')}</strong><span>{localize(record, '关键词、笔记和评论采集', 'Keywords, posts, and comments')}</span><ArrowRight size={16} /></button><button onClick={() => onNavigate(internalPath(record, '/douyin'))}><strong>{localize(record, '抖音内容工作流', 'Douyin workflow')}</strong><span>{localize(record, '视频、账号和评论采集', 'Videos, accounts, and comments')}</span><ArrowRight size={16} /></button><RouteButton record={record} onNavigate={onNavigate} path="/download" className="button button-dark">{localize(record, '从插件开始', 'Start with extension')}</RouteButton></div></section>
  </main>
}

function WelfareRecordPage({ record, onNavigate }) {
  const isEnglish = record.locale === 'en'
  const rewards = isEnglish ? [['Channel survey', 'Share how you found MediaClaw and help improve the public workflow.', Mail], ['Product feedback', 'Tell us what worked and what needs a clearer next step.', BadgeCheck], ['Partner referral', 'Explore the partner route when you are ready to share with your audience.', Link2]] : [['渠道问卷', '告诉我们你从哪里知道 MediaClaw，帮助改进公开工作流。', Mail], ['使用体验反馈', '说说哪里顺手、哪里还需要更清楚的下一步。', BadgeCheck], ['佣金推荐', '准备好向你的受众分享时，再了解伙伴计划路径。', Link2]]
  return <main className="commercial-record commercial-welfare-record">
    <CommercialHeader record={record} onNavigate={onNavigate} label={localize(record, '福利中心', 'Rewards')} />
    <section className="commercial-welfare-hero page-shell"><div><span className="commercial-eyebrow"><Gift size={15} /> {localize(record, '限时福利 · 公开说明', 'Limited offer · public description')}</span><h1>{record.h1}</h1><p>{record.summary}</p><div className="commercial-hero-actions"><PreviewAction icon={LockKeyhole}>{localize(record, '领取福利（预览）', 'Redeem reward (preview)')}</PreviewAction><RouteButton record={record} onNavigate={onNavigate} path="/referral" className="button button-soft">{localize(record, '了解伙伴计划', 'Explore partner program')}</RouteButton></div></div><div className="commercial-welfare-ticket"><span className="commercial-ticket-top">MediaClaw</span><strong>¥9</strong><span>{localize(record, '全能卡', 'All-in-one card')}</span><i>{localize(record, '采集 · 下载 · 分析 · 创作', 'Collect · download · analyze · create')}</i></div></section>
    <section className="commercial-welfare-benefits section-band"><div className="page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Zap size={15} /> {sectionText(record, 1, localize(record, '从采集下载，到分析创作，再到持续增长', 'From collection and download to analysis, creation, and growth'))}</span><h2>{localize(record, '一张卡，覆盖内容工作流的关键环节', 'One card for the key steps in a content workflow')}</h2></div><div className="commercial-benefit-grid"><article><Download size={20} /><h3>{sectionText(record, 2, localize(record, '无限量采集 / 下载', 'Unlimited collection / download'))}</h3><p>{localize(record, '先把公开样本和素材沉淀下来，后续分析才有可靠上下文。', 'Build a public sample and media library before analysis.')}</p></article><article><BarChart3 size={20} /><h3>{sectionText(record, 3, localize(record, '采集只是第一步，把数据变成选题和成稿', 'Collection is only the first step'))}</h3><p>{localize(record, '从标题、评论和素材中找出可以继续验证的选题线索。', 'Turn titles, comments, and media into ideas worth validating.')}</p></article><article><Clock3 size={20} /><h3>{sectionText(record, 4, localize(record, '不用每天刷账号，也能及时发现爆款和线索', 'Spot signals without checking accounts every day'))}</h3><p>{localize(record, '把监控、筛选和团队分配放进同一条可追溯路径。', 'Keep monitoring, filtering, and team handoff in one traceable path.')}</p></article></div><BoundaryNote record={record}>{localize(record, '福利领取、权益校验和支付未接入；此处只展示公开福利的内容层级，不会伪造领取成功。', 'Reward redemption, entitlement checks, and payment are not connected. This section shows the public offer hierarchy without claiming redemption.')}</BoundaryNote></div></section>
    <section className="commercial-welfare-extra page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Sparkles size={15} /> {sectionText(record, 5, localize(record, '全能卡之外，还能再多拿一点', 'A little more beyond the all-in-one card'))}</span><h2>{localize(record, '把反馈变成下一次更好的体验', 'Turn feedback into a better next experience')}</h2></div><div className="commercial-reward-grid">{rewards.map(([title, copy, Icon]) => <article key={title}><div className="commercial-icon-tile"><Icon size={20} /></div><h3>{title}</h3><p>{copy}</p><PreviewAction icon={LockKeyhole}>{localize(record, '入口未接入', 'Entry unavailable')}</PreviewAction></article>)}</div></section>
    <section className="commercial-record-cta"><div className="page-shell commercial-cta-row"><div><span className="commercial-eyebrow"><Download size={15} /> {localize(record, '从公开工作流开始', 'Start with the public workflow')}</span><h2>{localize(record, '先安装插件，再决定要不要领取福利', 'Install the extension first, then decide about the reward')}</h2></div><RouteButton record={record} onNavigate={onNavigate} path="/download" className="button button-dark">{localize(record, '安装插件', 'Install extension')}</RouteButton></div></section>
  </main>
}

function ReferralRecordPage({ record, onNavigate }) {
  const isEnglish = record.locale === 'en'
  const steps = isEnglish ? [['01', 'Get your referral link', 'A connected account would create a trackable link for your audience.'], ['02', 'Share on social media', 'Share a clear use case and link where your audience already follows you.'], ['03', 'Get cash rewards', 'The live service would verify eligible referrals and commission status.']] : [['01', '获取专属链接', '接入账户后，系统会为你的受众生成可追踪的分享链接。'], ['02', '社交媒体推广', '在你的受众已经关注的渠道，分享清楚的使用场景和链接。'], ['03', '坐享现金分成', '真实服务会核验有效推荐和返佣状态。']]
  return <main className="commercial-record commercial-referral-record">
    <CommercialHeader record={record} onNavigate={onNavigate} label={localize(record, '伙伴计划', 'Partner program')} />
    <section className="commercial-referral-hero page-shell"><div><span className="commercial-eyebrow"><Users size={15} /> {localize(record, '合作伙伴计划', 'Partner program')}</span><h1>{record.h1}</h1><p>{record.summary}</p><div className="commercial-hero-actions"><PreviewAction icon={LockKeyhole}>{localize(record, '立即参与并分享（预览）', 'Join and share (preview)')}</PreviewAction><RouteButton record={record} onNavigate={onNavigate} path="/download" className="button button-soft">{localize(record, '先安装插件', 'Install extension first')}</RouteButton></div></div><div className="commercial-referral-visual"><div className="commercial-referral-orbit"><Link2 size={30} /><span>MediaClaw</span></div><div className="commercial-referral-bubble one"><Users size={16} /> Creator</div><div className="commercial-referral-bubble two"><WalletCards size={16} /> Rewards</div><div className="commercial-referral-bubble three"><Globe2 size={16} /> Audience</div></div></section>
    <section className="commercial-referral-steps section-band"><div className="page-shell"><div className="commercial-section-heading"><span className="commercial-eyebrow"><Workflow size={15} /> {sectionText(record, 1, localize(record, '邀请机制说明', 'How it works'))}</span><h2>{localize(record, '从一次真实推荐开始', 'Start with one genuine recommendation')}</h2><p>{localize(record, '伙伴计划的关键是可追踪、可说明、可核验；本页把流程拆开，但不把未接入的返佣系统写成已运行。', 'A partner program needs traceability, context, and verification. This page shows the flow without pretending the commission system is live.')}</p></div><div className="commercial-referral-step-grid">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><Link2 size={19} /><h3>{title}</h3><p>{copy}</p></article>)}</div><BoundaryNote record={record}>{localize(record, '登录、专属链接生成、推荐归因和返佣结算未接入；参与按钮保持禁用，不会伪造加入成功。', 'Login, referral-link generation, attribution, and commission settlement are not connected. The join action stays disabled and never claims success.')}</BoundaryNote></div></section>
    <section className="commercial-referral-form page-shell"><div className="commercial-form-copy"><span className="commercial-eyebrow"><Mail size={15} /> {localize(record, '伙伴申请入口', 'Partner application')}</span><h2>{localize(record, '准备好开始了吗？', 'Ready to start promoting?')}</h2><p>{localize(record, '真实产品会在登录后收集伙伴信息；当前预览保留字段形状，方便评审接入前的页面结构。', 'The live product would collect partner details after sign-in. This preview keeps the field shape for integration review.')}</p></div><form className="commercial-preview-form" onSubmit={(event) => event.preventDefault()}><label>{localize(record, '你的称呼', 'Your name')}<input type="text" placeholder={localize(record, '预览字段', 'Preview field')} disabled /></label><label>{localize(record, '联系邮箱', 'Email')}<input type="email" placeholder="name@example.com" disabled /></label><label>{localize(record, '主要分享渠道', 'Primary channel')}<select disabled defaultValue=""><option value="">{localize(record, '选择渠道', 'Choose a channel')}</option></select></label><PreviewAction icon={Send}>{localize(record, '提交申请（未接入）', 'Submit application (not connected)')}</PreviewAction></form></section>
    <section className="commercial-record-cta"><div className="page-shell commercial-cta-row"><div><span className="commercial-eyebrow"><Sparkles size={15} /> MediaClaw</span><h2>{localize(record, '先了解产品，再分享给适合的人', 'Know the product before sharing it with the right people')}</h2></div><RouteButton record={record} onNavigate={onNavigate} path="/pricing" className="button button-dark">{localize(record, '查看价格方案', 'View pricing')}</RouteButton></div></section>
  </main>
}

export function CommercialRecordPage({ record, onNavigate = () => {} }) {
  if (!record || record.family !== 'commercial') return null
  const path = record.path.replace(/^\/en/, '')
  if (path === '/download') return <DownloadRecordPage record={record} onNavigate={onNavigate} />
  if (path === '/pricing') return <PricingRecordPage record={record} onNavigate={onNavigate} />
  if (path === '/features/feishu-integration') return <FeishuRecordPage record={record} onNavigate={onNavigate} />
  if (path === '/welfare') return <WelfareRecordPage record={record} onNavigate={onNavigate} />
  if (path === '/referral') return <ReferralRecordPage record={record} onNavigate={onNavigate} />
  return null
}
